stages:
- build
- sonarqube-check

build:
 stage: build
 script: 
  - cd Backend
  - ./gradlew build
  - ./gradlew.bat --stop

sonarqube-check:
  stage: sonarqube-check
  image: gradle:jre11-slim
  variables:
    SONAR_USER_HOME: "${Backend}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${do}"
    paths:
      - Backend/.sonar/cache
  script: 
    - cd Backend
    - gradlew sonarqube
  allow_failure: true
  only:
    - master # or the name of your main branch