stages:
- build
- sonarqube-check
- docker-build

build:
 stage: build
 script: 
  - cd Backend
  - ./gradlew build
  - ./gradlew.bat --stop

sonarqube-check:
  stage: sonarqube-check
  image: gradle:jre11-slim
  variables:
    SONAR_USER_HOME: "${Backend}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${do}"
    paths:
      - Backend/.sonar/cache
  script: 
    - cd Backend
    - ./gradlew sonarqube
    - ./gradlew.bat --stop
  allow_failure: true
  only:
    - master # or the name of your main branch

docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
